# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: carrito.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'carrito.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcarrito.proto\x12\x07\x63\x61rrito\"\x07\n\x05\x45mpty\"U\n\x0bItemRequest\x12\x10\n\x08producto\x18\x01 \x01(\t\x12\x0e\n\x06precio\x18\x02 \x01(\x02\x12\x10\n\x08\x63\x61ntidad\x18\x03 \x01(\x05\x12\x12\n\ncliente_id\x18\x04 \x01(\t\"#\n\rVaciarRequest\x12\x12\n\ncliente_id\x18\x01 \x01(\t\"A\n\x0bItemDetalle\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61ntidad\x18\x02 \x01(\x05\x12\x10\n\x08subtotal\x18\x03 \x01(\x02\">\n\rProductoStock\x12\x0e\n\x06nombre\x18\x01 \x01(\t\x12\r\n\x05stock\x18\x02 \x01(\x05\x12\x0e\n\x06precio\x18\x03 \x01(\x02\"P\n\x12InventarioResponse\x12)\n\tproductos\x18\x01 \x03(\x0b\x32\x16.carrito.ProductoStock\x12\x0f\n\x07version\x18\x02 \x01(\x05\"\x86\x01\n\x0f\x43\x61rritoResponse\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\x12\x17\n\x0ftotal_articulos\x18\x02 \x01(\x05\x12\x12\n\ngran_total\x18\x03 \x01(\x02\x12&\n\x08\x64\x65sglose\x18\x04 \x03(\x0b\x32\x14.carrito.ItemDetalle\x12\r\n\x05\x65xito\x18\x05 \x01(\x08\x32\xd1\x01\n\rGestorCarrito\x12?\n\x0b\x41gregarItem\x12\x14.carrito.ItemRequest\x1a\x18.carrito.CarritoResponse\"\x00\x12;\n\x05Pagar\x12\x16.carrito.VaciarRequest\x1a\x18.carrito.CarritoResponse\"\x00\x12\x42\n\x11ObtenerInventario\x12\x0e.carrito.Empty\x1a\x1b.carrito.InventarioResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'carrito_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_ITEMREQUEST']._serialized_start=35
  _globals['_ITEMREQUEST']._serialized_end=120
  _globals['_VACIARREQUEST']._serialized_start=122
  _globals['_VACIARREQUEST']._serialized_end=157
  _globals['_ITEMDETALLE']._serialized_start=159
  _globals['_ITEMDETALLE']._serialized_end=224
  _globals['_PRODUCTOSTOCK']._serialized_start=226
  _globals['_PRODUCTOSTOCK']._serialized_end=288
  _globals['_INVENTARIORESPONSE']._serialized_start=290
  _globals['_INVENTARIORESPONSE']._serialized_end=370
  _globals['_CARRITORESPONSE']._serialized_start=373
  _globals['_CARRITORESPONSE']._serialized_end=507
  _globals['_GESTORCARRITO']._serialized_start=510
  _globals['_GESTORCARRITO']._serialized_end=719
# @@protoc_insertion_point(module_scope)
