# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import carrito_pb2 as carrito__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in carrito_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GestorCarritoStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AgregarItem = channel.unary_unary(
                '/carrito.GestorCarrito/AgregarItem',
                request_serializer=carrito__pb2.ItemRequest.SerializeToString,
                response_deserializer=carrito__pb2.CarritoResponse.FromString,
                _registered_method=True)
        self.Pagar = channel.unary_unary(
                '/carrito.GestorCarrito/Pagar',
                request_serializer=carrito__pb2.VaciarRequest.SerializeToString,
                response_deserializer=carrito__pb2.CarritoResponse.FromString,
                _registered_method=True)
        self.ObtenerInventario = channel.unary_unary(
                '/carrito.GestorCarrito/ObtenerInventario',
                request_serializer=carrito__pb2.Empty.SerializeToString,
                response_deserializer=carrito__pb2.InventarioResponse.FromString,
                _registered_method=True)


class GestorCarritoServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AgregarItem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pagar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerInventario(self, request, context):
        """Nueva función para que todos los clientes sepan qué hay en stock
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GestorCarritoServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AgregarItem': grpc.unary_unary_rpc_method_handler(
                    servicer.AgregarItem,
                    request_deserializer=carrito__pb2.ItemRequest.FromString,
                    response_serializer=carrito__pb2.CarritoResponse.SerializeToString,
            ),
            'Pagar': grpc.unary_unary_rpc_method_handler(
                    servicer.Pagar,
                    request_deserializer=carrito__pb2.VaciarRequest.FromString,
                    response_serializer=carrito__pb2.CarritoResponse.SerializeToString,
            ),
            'ObtenerInventario': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerInventario,
                    request_deserializer=carrito__pb2.Empty.FromString,
                    response_serializer=carrito__pb2.InventarioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'carrito.GestorCarrito', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('carrito.GestorCarrito', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GestorCarrito(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AgregarItem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carrito.GestorCarrito/AgregarItem',
            carrito__pb2.ItemRequest.SerializeToString,
            carrito__pb2.CarritoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pagar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carrito.GestorCarrito/Pagar',
            carrito__pb2.VaciarRequest.SerializeToString,
            carrito__pb2.CarritoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerInventario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carrito.GestorCarrito/ObtenerInventario',
            carrito__pb2.Empty.SerializeToString,
            carrito__pb2.InventarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
